
import sys
from pathlib import Path

rename_full = {
    "addrSpaceCast"      : "addrspacecast",
    "addWithOverflow"    : "addwithoverflow",
    "alignCast"          : "aligncast",
    "alignOf"            : "alignof",
    "as"                 : "as",
    "atomicLoad"         : "atomicload",
    "atomicRmw"          : "atomicrmw",
    "atomicStore"        : "atomicstore",
    "bitCast"            : "bitcast",
    "bitOffsetOf"        : "bitoffsetof",
    "bitSizeOf"          : "bitsizeof",
    "branchHint"         : "branchhint",
    "breakpoint"         : "breakpoint",
    "mulAdd"             : "muladd",
    "byteSwap"           : "byteswap",
    "bitReverse"         : "bitreverse",
    "offsetOf"           : "offsetof",
    "call"               : "call",
    "cDefine"            : "cdefine",
    "cImport"            : "cimport",
    "cInclude"           : "cinclude",
    "clz"                : "clz",
    "cmpxchgStrong"      : "cmpxchgstrong",
    "cmpxchgWeak"        : "cmpxchgweak",
    "compileError"       : "compileerror",
    "compileLog"         : "compilelog",
    "constCast"          : "constcast",
    "ctz"                : "ctz",
    "cUndef"             : "cundef",
    "cVaArg"             : "cvaarg",
    "cVaCopy"            : "cvacopy",
    "cVaEnd"             : "cvaend",
    "cVaStart"           : "cvastart",
    "divExact"           : "divexact",
    "divFloor"           : "divfloor",
    "divTrunc"           : "divtrunc",
    "embedFile"          : "embedfile",
    "enumFromInt"        : "enumfromint",
    "errorFromInt"       : "errorfromint",
    "errorName"          : "errorname",
    "errorReturnTrace"   : "errorreturntrace",
    "errorCast"          : "errorcast",
    "export"             : "export",
    "extern"             : "extern",
    "field"              : "field",
    "fieldParentPtr"     : "fieldparentptr",
    "FieldType"          : "FieldType",
    # "FieldType"          : "fieldtype",
    "floatCast"          : "floatcast",
    "floatFromInt"       : "floatfromint",
    "frameAddress"       : "frameaddress",
    "hasDecl"            : "hasdecl",
    "hasField"           : "hasfield",
    "import"             : "import",
    "inComptime"         : "incomptime",
    "intCast"            : "intcast",
    "intFromBool"        : "intfrombool",
    "intFromEnum"        : "intfromenum",
    "intFromError"       : "intfromerror",
    "intFromFloat"       : "intfromfloat",
    "intFromPtr"         : "intfromptr",
    "max"                : "max",
    "memcpy"             : "memcpy",
    "memset"             : "memset",
    "min"                : "min",
    "wasmMemorySize"     : "wasmmemorysize",
    "wasmMemoryGrow"     : "wasmmemorygrow",
    "mod"                : "mod",
    "mulWithOverflow"    : "mulwithoverflow",
    "panic"              : "panic",
    "popCount"           : "popcount",
    "prefetch"           : "prefetch",
    "ptrCast"            : "ptrcast",
    "ptrFromInt"         : "ptrfromint",
    "rem"                : "rem",
    "returnAddress"      : "returnaddress",
    "select"             : "select",
    "setEvalBranchQuota" : "setevalbranchquota",
    "setFloatMode"       : "setfloatmode",
    "setRuntimeSafety"   : "setruntimesafety",
    "shlExact"           : "shlexact",
    "shlWithOverflow"    : "shlwithoverflow",
    "shrExact"           : "shrexact",
    "shuffle"            : "shuffle",
    "sizeOf"             : "sizeof",
    "splat"              : "splat",
    "reduce"             : "reduce",
    "src"                : "src",
    "sqrt"               : "sqrt",
    "sin"                : "sin",
    "cos"                : "cos",
    "tan"                : "tan",
    "exp"                : "exp",
    "exp2"               : "exp2",
    "log"                : "log",
    "log2"               : "log2",
    "log10"              : "log10",
    "abs"                : "abs",
    "floor"              : "floor",
    "ceil"               : "ceil",
    "trunc"              : "trunc",
    "round"              : "round",
    "subWithOverflow"    : "subwithoverflow",
    "tagName"            : "tagname",
    "This"               : "This",
    # "This"               : "this",
    "trap"               : "trap",
    "truncate"           : "truncate",
    "typeInfo"           : "typeinfo",
    "typeName"           : "typename",
    "Type"               : "Type",
    # "Type"               : "type",
    "TypeOf"             : "TypeOf",
    # "TypeOf"             : "typeof",
    "unionInit"          : "unioninit",
    "Vector"             : "Vector",
    # "Vector"             : "vector",
    "volatileCast"       : "volatilecast",
    "workGroupId"        : "workgroupid",
    "workGroupSize"      : "workgroupsize",
    "workItemId"         : "workitemid",
}

# rename = {o: r for o, r in rename_full.items() if o != r}
rename = {o: r for o, r in rename_full.items()}

for path in sys.argv[1:]:
    path = Path(path)
    print(f"renaming {path}")

    try:

        with path.open("r") as f:
            contents = f.read()

        for o, r in rename.items():
            replaced = contents.replace(o, r)

        with path.open("w") as f:
            f.write(replaced)

    except Exception:
        print(f"error: skipping {path}")

